version: '3.8'

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=artemisadmin
      - POSTGRES_PASSWORD=artemaki
      - POSTGRES_DB=agendaCraft
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-U", "artemisadmin", "-d", "agendaCraft" ]
      interval: 5s
      timeout: 5s
      retries: 5

  restore-service:
    image: postgres:latest
    container_name: restore-container
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      -  restore-flag:/restore-flag

    environment:
      - PGPASSWORD=artemaki
    depends_on:
      psql-db:
        condition: service_healthy  # Only depend on psql-db when it's healthy
    command: >
      bash -c "
      if [ ! -f /restore-flag/restored.txt ]; then
        while ! pg_isready -h psql-db -p 5432 -U artemisadmin; do sleep 1; done;
        pg_restore --host=psql-db --port=5432 --username=artemisadmin --dbname=agendaCraft --no-owner --verbose /docker-entrypoint-initdb.d/agendaCraft.dump
        touch /restore-flag/restored.txt
      fi"

  agendacraft:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agendaCraft_app
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/agendaCraft
      - SPRING_DATASOURCE_USERNAME=artemisadmin
      - SPRING_DATASOURCE_PASSWORD=artemaki
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy  # Only depend on psql-db when it's healthy
    command: ["java", "-jar", "agendaCraft.jar"]

volumes:
  postgres-data:
  restore-flag:
